#!/bin/bash

if ! [[ -f ".env" ]]
then
	echo ".env file not found, please run setup"
	exit 1
fi

DOCKER_COMMAND=${1:-"up"}

OVERRIDE_FILE=""

file="./docker-compose.override.yml"
if [ -f "$file" ]
then
	echo "Using docker-compose.override.yml"
	OVERRIDE_FILE="-f docker-compose.override.yml"
else
	echo "No override found"
fi
shift

COMMAND="docker compose -f docker-compose.yml ${OVERRIDE_FILE} ${DOCKER_COMMAND} $*"
echo "executing: ${COMMAND}"
${COMMAND}
