version: "3.1"
services:
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "3001:8025"

  redis:
    image: "redis:alpine"
    volumes:
        - redis:/data

  mysql:
    image: "mysql:latest"
    volumes: 
        - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=database
      - MYSQL_PASSWORD=database
    ports:
      - "3002:3306"

  nginx:
    image: "nginx:alpine"
    working_dir: /app
    volumes:
      - "./app:/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./volumes/nginx/log:/var/log/nginx/"
    ports:
      - "3000:80"
    depends_on:
        - php

  php:
    build:
      context: ./docker/php
      args:
        UID: ${UID}
        USER: ${USER}
    working_dir: /app
    depends_on:
      - mysql
      - redis
    volumes:
      - "./app:/app"
      - "./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"

volumes:
    redis: {}
    mysql: {}
